server:
  port: 8088

 
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@172.16.59.195:1521:ncdb
    username: NC0512
    password: NC0512
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.wanghuan.model.sys